#title: SERVICE combining playground with main dataset
SELECT *
WHERE {
	SERVICE <http://sparql.uniprot.org/sparql/> {
		SELECT * WHERE {
			?protein up:organism taxon:9606 ;
				 up:reviewed true
		} LIMIT 2
	}
}
