#title:UNION (OR inclusive)
SELECT ?taxon ?rank
WHERE
{
	?taxon a up:Taxon .
        ?taxon up:rank ?rank .
        {
	       ?taxon up:ramk up:Genus .
        } UNION {
               ?taxon up:rank up:Species . 
        }
}
