#title:Who are the persons in this family?
#comment:selects all subjects whose type is dbo:Person
#img:family.png
#tags:rdf:type

select ?person where {
    ?person rdf:type dbo:Person .
    #instead of using rdf:type, you can also use the synonym "a":
    #?person a dbo:Person . 
}
