#title:What is the age of every person?
#comment:Use the function now() and year() and BIND
#img:family.png
#tags:functions, year, now

select ?person ?age where {
    ?person rdf:type dbo:Person .
	?person dbp:birthDate ?birth .
  	BIND ((year(now()) - year(?birth)) AS ?age)
}
order by ?age