#title:Select all the people who are 65 years or less
#comment:Traverse the graph
#tags:filter

select ?person ?age where {
    ?person rdf:type dbo:Person .
	?person dbp:birthDate ?birth .
  	BIND ( ( year(now()) - year(?birth) ) AS ?age ).
	filter (?age > 18 && ?age < 65)
}
