#title:Select UniProt records with a related disease
#tags: Swiss-Prot, UniProtKB, Disease
SELECT ?protein ?disease
WHERE {?protein a up:Protein;
                up:annotation ?annotation .
       ?annotation up:disease ?disease}
