#title:MINUS all data (note lack of overlap in variables)
#color:ex-red 
SELECT ?subject ?predicate ?object
WHERE
{
	?subject ?predicate ?object
        MINUS {
       		?msubject ?mpredicate ?mobject
	} 
} LIMIT 10
