#title:Select UniProt records with a related disease plus more information about the disease
#id:4b
SELECT ?protein ?disease ?comment ?diseaseComment ?omimEtc
WHERE {?protein a up:Protein;
                up:annotation ?annotation .
       ?annotation up:disease ?disease ;
                rdfs:comment ?comment .
       ?disease rdfs:seeAlso ?omimEtc ;
                rdfs:comment ?diseaseComment ;
}
