#title:Negation 3: FILTER NOT BOUND/SPARQL 1.0
#color:ex-red 
SELECT ?taxon ?rank
WHERE
{
	?taxon up:rank ?rank
	OPTIONAL {
		?taxon up:rank up:Genus ;
                       up:rank ?genus .
        }
	FILTER(! BOUND (?genus))
} LIMIT 10
