#title: FILTER using implicit and
#color:ex-red 
SELECT ?taxon ?name
WHERE {
  ?taxon a up:Taxon .
  ?taxon up:scientificName ?name .
  FILTER(?name != "Marmota") 
  FILTER (?name != "Marmota marmota" )
}    
