#title: Example CONSTRUCT making new triples
#color:ex-yellow 
#tags:Does not work
#comment:CONSTRUCT is not suported by the playground
CONSTRUCT {
	?taxon a <http://example.org/coolCreature> 
} WHERE {
	?taxon up:scientificName ?name .
	FILTER(contains(?name, "Marmot")
}
