#title: Constructing an owl:sameAs between two IRI (this is an example wrong in practice)
#color:ex-yellow 
#tags:Does not work
#comment:CONSTRUCT does not work in the playground try it at sparql.uniprot.org
CONSTRUCT {
	?taxon owl:sameAs ?ncbi
} WHERE {
	?taxon a up:Taxon .
	BIND("http://www.ncbi.nlm.gov/taxonomy/" AS ?base)
	BIND(IRI(CONCAT(?base, substr(?taxon, 34) AS ?ncbi)
}
