#title:Which classes have instances?
#comment:Counts the number of instances per class
#tags:class, instance

SELECT ?class (count(?instance) as ?numberOfInstances) 
WHERE {
    ?instance a ?class .
}
group by ?class
order by desc(?numberOfInstances) 
