#title:How to get the declared properties
#comment:Selects the declared properties. 
#comment:Note that the dataset may be using properties that are not "declared" (they may be declared in other dataset see FAQ7)

SELECT ?property
WHERE {
    ?property a rdf:Property . 
}