#title:Which classes have instances?
#comment:Selects subjects described with the tto:weight predicate. ?thing, ?name are the variables
#comment:?thing, ?name are the variables
#tags:owl class, instance

SELECT DISTINCT ?class
WHERE {
    ?instance a ?class .
}
ORDER by ?class