#title:How many instances of a certain class are declared?
#comment:To count the number of instances of a particular class you can use the keyword COUNT with the name of the class
    
SELECT (COUNT(?s) AS ?totalNumberOfInstances)
WHERE { ?s ?p tto:Animal } 
#replace tto:Animal with the name of the class