#title:Which Classes Use a Particular Property?
#comment:Selects subjects described with the tto:weight predicate. ?thing, ?name are the variables, 
#comment:each filter removes some solutions in turn according to the ?weight value
#tags:rdf property
    
SELECT DISTINCT ?class
WHERE {
    ?s dbp:name ?o ;
    a ?class .
}

# may be worth to include rdfs:label, rdfs:comment or 
# rdfs:domain to get even more knowledgeable data