#title:Stats about properties
#comment:This query tells for each property how many times it has been use. This is a very expensive query, therefore use it with care

SELECT ?property (COUNT(?property) AS ?propTotal)
WHERE { ?s ?property ?o . }
GROUP BY ?property
ORDER BY DESC(?propTotal)