#id:NXQ_00063
#title:Proteins that have at least one RRM RNA-binding domain and either no GO "RNA binding" or a GO "RNA binding" with evidence cv:ECO_0000501 or cv:ECO_0000250
#tags:domain,region,evidence,GO
#acs:Q14103, Q6ZRY4, Q8TC92, ...
#count:78
#time: 0.1

select distinct ?entry where {
  {
    ?entry :isoform ?iso.
    # >=1 RRM RNA-binding domain
    ?iso :region/:term cv:DO-00581.
    # No GO "RNA binding" 
    filter not exists {
      ?iso :function/:term /:childOf cv:GO_0003723
    }
  }
  union{
    ?entry :isoform ?iso.
    # >=1 RRM RNA-binding domain
    ?iso :region/:term cv:DO-00581.
    # GO "RNA binding" with evidence IEA or ISS
    ?iso :function ?s1.
    ?s1 :term /:childOf cv:GO_0003723.
    ?s1 :evidence /:evidenceCode /:childOf ?pcode.
    values ?pcode { cv:ECO_0000501 cv:ECO_0000250 }
  }
}

