#id:NXQ_00014
#title:Proteins with one SH2 and two SH3 domains
#tags:domain,region
#acs:O75791,P15498,P16333,P46108,P46109,P52735,P62993,Q13588,Q9UKW4
#count:9

select distinct ?entry where {
  ?entry :isoform ?iso.
  #with 1 SH3
  {select ?iso where{?iso :region ?stat1. ?stat1 :term cv:DO-00614
  } group by ?iso having(count( ?stat1)=1)}
  #with 2 SH2
  {select ?iso where{?iso :region ?stat2. ?stat2 :term cv:DO-00615
  } group by ?iso having(count( ?stat2)=2)}
} group by ?entry
