#id:NXQ_00044
#title:Proteins involved in the Reactome pathway "Respiratory electron transport"
#tags:pathway
#acs:P12074,O75306,Q9P0S2
#count:86
#time:0.3

select distinct ?entry where {
  ?entry :isoform / :function / a :Pathway.
  ?entry :reference ?ref.
  ?ref a :Xref.
  ?ref :provenance db:Reactome; :accession "REACT_22393"^^xsd:string.
}
