#id:NXQ_00055
#title:Proteins which have genes of length greater than 2 million bp
#tags:gene
#acs:Q15700,Q9UHC6,A1Z1Q3, ...
#count:7
#time:0.1

select distinct ?entry where {
  ?entry :gene / :length ?l.
  filter (?l > 2000000)
}
