#id:NXQ_00118
#title:Proteins with at least one somatic variant
#comment:In this query we consider all COSMIC mutation to be somatic (which is not alwasy the case!).
#tags:variant,sequence variation
#acs:Q9Y6X6,Q9NYV4,Q9NZ52
#count:17914
#time:9.9

select distinct ?entry where {
 ?entry :isoform ?iso.
 ?iso :variant ?var.
 { 
 ?var rdfs:comment ?comment.
 filter (contains (?comment,'somatic'))
 }
 union
 {
 ?var :evidence ?ev.
 ?ev :assignedBy source:Cosmic.
 }
}
