#id:NXQ_00038
#title:Proteins with at least one selenocysteine in their sequence
#tags:selenocysteine,sequence
#acs:O60613, Q99611, Q9NZV6, ...
#count:26
#time:0.1

select distinct ?entry where {
  ?entry :isoform/:selenocysteine ?statement.
}
