#id:NXQ_00074
#title:Proteins belonging to a family with at least two members in the human proteome
#tags:family
#acs:Q8NEK5, Q96P63, Q92630, ...
#count:5416
#time: 4.7

select distinct ?entry where {
  ?entry :family/:accession/:childOf ?ac.
  ?member :family/:accession/:childOf ?ac.
} group by ?entry having (count(distinct ?member) >= 2 )
