#id:NXQ_00078
#title:Proteins which have been identified in at least one proteomics set and that are secreted
#tags:subcellular location,cellular component,proteomics,mass spectrometry
#acs:P40933, A1L453, A6NNL5, ...
#count:1835
#time: 0.13

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :cellularComponent/:term/:childOf cv:SL-0243.
  ?iso :peptideMapping ?map.
}

