#id:NXQ_00013
#title:Proteins that have a protein kinase domain but lack protein kinase activity
#tags:domain,region,function,enzyme
#acs:O15197,O43187,P16066,P20594,P25092,P51841,Q02846,Q05823,Q13308,Q496M5
#count:29

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :region /:term cv:DO-00529.
  filter not exists { ?iso :enzymeClassification / :term /:childOf cv:2_7_-_- }
}
