#id:NXQ_00037
#title:Proteins that bind RNA but do not contain a RRM domain
#tags:domain,region
#acs:P08621, P14678, Q96B26, ...
#count:453
#time:0.1

select distinct ?entry where {
  ?entry :isoform ?iso;:classifiedWith cv:KW-0694. #RNA-binding
  filter not exists {?iso :region/:term cv:DO-00581} #RRM
}
