#id:NXQ_00054
#title:Proteins which are "Receptor binding" according to GO and have the Swiss-Prot keyword "Immunity"
#tags:function,GO,keyword
#acs:P05771, O60602, Q13114, ...
#count:72
#time: 0.1

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :function ?statement.
  ?statement :term / :childOf cv:GO_0005102.
  ?iso :keyword/:term cv:KW-0391.
}
