#id:NXQ_00202
#title:Proteins with from 2 to 4 transmembrane regions
#tags:domain,region,transmembrane,topology
#acs:Q6ZT12, ...
#count:1097
#time:0.3

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :topology ?statement.
  ?statement a :TransmembraneRegion.
} group by ?entry ?iso having(count( ?statement)>=2 && count( ?statement)<=4)

