#id:NXQ_00130
#title:Proteins with a DNA-binding region but not located in the nucleus
#tags:DNA-binding,region,domain,subcellular location,cellular component
#acs:P02751,Q96LU7,Q9BXR3
#count:14
#time:0.1

select distinct ?entry where {
  ?entry :isoform ?iso.
  ?iso :dnaBindingRegion ?dnab.
  filter not exists { ?entry :isoform / :subcellularLocation /:term /:childOf cv:SL-0191}.  
}
