#id:NXQ_00031
#title:Get William's friends (using predicate path tto:friend)
#comment:retrieves solutions for objects connected to the subject ttr:William with the tto:friend predicate
#tags:1 graph pattern,1 variable

select * where {
  ttr:William tto:friend ?friend.
}