#id:NXQ_00026
#title:Get the count of individuals by species for those having more than one member 
#comment:the graph pattern matching process generates the possible solutions as a list of ?species and ?member values tuples
#comment:then for each ?species value (grouping criterion), the ?member values are counted with the aggregate function COUNT()
#comment:finally the result is filtered with the HAVING expression i order to keep only those species having more than one member
#tags:2 graph patterns,2 variables,GROUP BY,aggregate function COUNT(),HAVING

select ?species (COUNT(?member) as ?memberCount)  where {
  ?species owl:subClassOf tto:Animal .
  ?member rdf:type ?species .
}
GROUP BY ?species
HAVING (?memberCount > 1)
