#id:NXQ_00009
#title:Select things that have a weight between 5 and 7 kg
#comment:Selects subjects described with the tto:weight predicate. ?thing, ?name are the variables, 
#comment:the filter defines 2 criteria to be met for the ?weight value to remove some solutions
#tags:1 graph pattern,2 variables,FILTER,logical AND : &&
    
select ?thing ?weight where {
  ?thing tto:weight ?weight .
  FILTER (?weight > "5.0"^^xsd:decimal && ?weight < "7.0"^^xsd:decimal) 
}
