#title:Get list of 4 instances in the dataset 
#comment:The LIMIT modifier sets an upper bound to the number of solutions returned.
#comment:The ORDER BY clause is applied on the full set of solutions. The LIMIT modifier is taken into account
#comment:after the ORDER BY clause.
#tags:1 graph pattern,2 variables,ORDER BY,LIMIT
#color:ex-yellow

SELECT ?class ?instance WHERE {
  ?instance rdf:type ?class . 
}
ORDER BY ?class ?instance
LIMIT 4

#can also use 'a' instead of 'rdf:type'
