#id:NXQ_00013
#title:Select persons with their name only if they have a pet
#comment:Selects subjects with their name if the subject has a pet. ?person, ?name ?pet are the variables
#comment: note that the ?pet value is bound in the FILTER scope but is not bound in the SELECT scope 
#tags:2 graph patterns,3 variables,FILTER EXISTS
    
select ?person ?name ?pet where {
	?person rdf:type dbo:Person .
	?person dbp:name ?name .
	FILTER EXISTS { ?person tto:pet ?pet}
}
