#id:NXQ_00018
#title:William's and John's pets
#comment:Selects the UNION of the solutions found for two separate graph patterns. ?pet is the variable
#tags:2 graph patterns,1 variable,UNION
    
select ?pet where {
	{ 
		ttr:William tto:pet ?pet .
	} UNION {
		ttr:John tto:pet ?pet .
	}
}
