#title:Select all things that are females
#comment:Selects subjects connected to the object dbo:Person via the predicate rdf:type
#comment:?thing is the only variable
#tags:1 graph pattern,1 variable
#img:cartoon-female
#color:ex-blue
    
select ?thing where {
  ?thing tto:sex "female" .
}

#Takes as well the pets
