#id:NXQ_00020
#title:Select people with their gender and birth date orderd by gender and birth date (oldest first) 
#comment: by default the direction of ORDER BY is ascending (asc), use desc() to use descending direction. 
#tags:4 graph patterns,3 variables,ORDER BY

select ?people ?sex ?birth ?name where {
  ?people rdf:type dbo:Person .
  ?people dbp:name ?name .
  ?people tto:sex ?sex . 
  ?people dbp:birthDate ?birth . 
}
ORDER BY ?sex desc(?birth)
