#title:Select things that are persons and are female (women)
#comment:Selects subjects connected to the object dbo:Person via the predicate rdf:type and
#comment:use the same variable '?thing' to connect to the literal female by the predicated tto:sex.
#tags:1 graph pattern,1 variable, 2 conditions
#color:ex-blue
    
select ?thing where {
  ?thing a dbo:Person .
  ?thing tto:sex "female" .
}


# Use the same name of the variable in the 2 statements
# It is the name of the variable that enforces the constraint

# Hint: Use the semicolon ';' to refer to the previous subject 
#
# select ?thing where {
#  ?thing a dbo:Person ;
#   		tto:sex "female" .
#}


# Note that we could also use the comma ',' , if we had hermaphrodites in our dataset
# The following statements selects things that are persons male and females at the same time:
# select ?thing where {
#  ?thing a dbo:Person ;
#   		tto:sex "female" , "male" 
#}
#Of course this does not return any value in our "normal" dataset....