#title:Select persons and their name
#comment:Selects subjects and objects connected with the predicate dbp:name,
#comment:?thing and ?name are the variables
#tags:1 graph pattern,2 variables
#color:ex-blue
    

select ?person ?name where {
    ?person rdf:type dbo:Person .
	?person dbp:name ?name .
}
