#title:William's and John's pets 
#comment:Selects the pets of a list of owners using the clause union or values
#tags:1 graph pattern,1 variable,values,union
#color:ex-blue
#img:cartoon-rdf-type


select ?pet where {	
	{ 
		ttr:William tto:pet ?pet .
	} UNION {
		ttr:John tto:pet ?pet .
	}
}

# In this scenario we only have 2 persons who have pets, so it is not the best example
# but you could see the potential of union in a real scenario, where we would have many owners and we would 
# like to filter just a few of them
#
# Alternatively you can also use the keyword VALUES (faster option)
#
# select ?owner ?pet where {
#	VALUES (?owner) { (ttr:William) (ttr:John) }
#	?owner tto:pet ?pet .
#}

