#title:Select persons and, if they have, their pets as well
#comment:Similar to the previous one, but putting the
#comment:the triplet linked with tto:pet inside the optional clause
#tags:1 graph pattern,2 variables,2 conditions,optional
#color:ex-blue
#img:cartoon-rdf-type

select ?person ?pet where {
    ?person rdf:type dbo:Person .
	optional {?person tto:pet ?pet }.
}

# The use of the clause optional allows
# to extract their pets if they exist
# but will not exclude the persons who don't have pets
