#title:Select Eve's grandfather
#comment:Use the property dbo:parent
#tags:exercise,2 graph patterns,3 variables,FILTER EXISTS
   
select ?grandfather where {
	ttr:Eve dbo:parent  *** .
	***	  	     ***   ?grandfather  .
}

# Once you get ttr:John,
# try to write the expression in only one line using '/'
# knowing that:
#
#             ?a prop ?c .
#			  ?c prop ?d .
#
# can be simplified like this:
#
#             ?a prop / prop ?d
