#title: ***BONUS*** Select William's relatives 
#comment:Join the results of William's parent and people who has William as parent
#comment:Explore the property inverse path on alternative B) ^ .
#comment:Explore the use of the pipe in alternative C) | .
#tags:1 graph pattern,1 variable,path syntax : inverse path ^,path syntax : alternative path |

select ?relative where {
  {ttr:William *** ?relative} 
  *** 
  {?relative *** ttr:William} 
}

# B) 
#
# Once you get ttr:Eve and ttr:John try to explore the use of inverse path ^
#
# knowing that:
#
# 			?a :prop ?b
#
# is equivalent:
#
# 			?b ^:prop ?a

# C) 
#
# Once B) done, try to write the query in one line using the pipe (|) which means OR
#
#  ttr:William (prop | ^prop) ?relative
