#title:Select persons and their names only if they have a pet who is a cat
#comment:Selects subjects with their name but removes solutions. ?person, ?name ?pet are the variables
#comment: note that the ?pet value is bound in the FILTER scope but is not bound in the SELECT scope 
#tags:exercise,2 graph patterns,3 variables,FILTER EXISTS
   
select ?person ?name where {
	?person rdf:type dbo:Person .
	?person dbp:name ?name .
	*** *** { 
		?person tto:pet / rdf:type *** .
	}
}

# Alternatively try to return the 2 cats of John ?pet
# along with the variable ?person and ?name
# remember that variables can not be defined inside filter exists