#title:Select persons who don't have cats
#comment:You should filter out any person with a pet which is of type tto:Cat
#tags:exercise,2 graph patterns,3 variables,filter not exists
   
select ?person where {
	?person rdf:type dbo:Person .
	*** *** *** { 
		?person tto:pet / rdf:type *** .
	}
}

# B)
# Once you get ttr:William and ttr:Eve try to reply to this question:
# Select persons who have pets and those pets are not cats
# You should get only ttr:William (because Eve does not have any pet)
# remember that variables are not bound inside a filter clause