#title:Select things that are persons
#comment:Selects subjects connected to the object dbo:Person via the predicate rdf:type
#comment:?thing is the only variable
#tags:1 graph pattern,1 variable
#color:example-red
    
select ?thing where {
  ?thing rdf:type dbo:Person .
}
