#title:Select all instances that are animals
#comment:Hint:use the property rdfs:subClassOf+, rdf:type and the class tto:Animal
#tags:1 graph pattern,2 variables,FILTER,logical not equals : !=
#color:ex-yellow

select ?thing ?type where {
  ?thing a ?type .
  ?type rdfs:subClassOf+ tto:Animal .
}

# or simply 
#
# select ?thing ?type where {
#  ?thing a / rdfs:subClassOf+ tto:Animal .
#}
