#title:Select things with their name and their fur color (if exists)
#comment:Selects things described with both the dbp:name and tto:color predicates, use the key optional to get also the persons
#comment:?thing, ?name, ?color are the variables
#tags:2 graph patterns,3 variables,optional
#color:ex-red
    
select ?thing ?name ?color where {
  ?thing dbp:name ?name .
  optional { ?thing tto:color ?color }.
}

