#title:Get the direct and indirect sub classes of class Creature
#comment:the + after rdfs:subClassOf retrieves solutions for ?species if it is connected to tto:Creature by one or multiple owl:subClassOf predicates
#tags:1 graph pattern,1 variable,path syntax : 1-n paths +
#img:ontology
#color:ex-yellow

select ?subSpecies   where {
  ?subSpecies rdfs:subClassOf+ tto:Creature .
}

# There are different ways to express the property path level
#
# path+ | path+ | path*
#
#  * -> means 0 or more
#  + -> means 1 or more
#  ? -> means 0 or 1 

# The same can be used for any property for example:
# select ?parents where {
#	ttr:Eve dbo:parent+ ?parents .
# }