#id:NXQ_00039
#title:Get creature names starting with either B of F and ending with either x or y
#comment: uses a regex pattern (regular expressions) to find names meeting a complex criterion
#tags:1 graph pattern,2 variables,FILTER,string function regex()

select * where {
  ?creature dbp:name ?name .
  FILTER ( REGEX(?name, "^[BF].*[xy]$" ) )
} 

