#title:Celebrities born on the 13-07-1942 with their birth date, occupation and their pets if any
#comment:People born on the 13-07-1942 are retrieved from dbpedia using a federated query  
#comment:through the SERVICE keyword. The graph retrieved is combined with the local graph
#comment:and solutions are built from the distant and local graph pattern matching processes.
#comment:The local graph pattern here is optional so that we can see celebrities for which
#comment:we don't know about their pets.
#tags:1 graph pattern,VALUES,OPTIONAL,SERVICE

select *  where {
    SERVICE <http://dbpedia.org/sparql> {
      select ?person ?birthDate ?occupation ?pet where {
        VALUES ?birthDate { "1942-07-13"^^xsd:date }
        ?person dbp:birthDate ?birthDate .
        ?person dbp:occupation ?occupation .
      } 
    }
    OPTIONAL { ?person tto:pet ?pet } .
} 
