#title:Search for lonely pets and try to find them a nice owner :)

#comment: Insert the triplet using the data tab (you must run the web application locally)
#This query shows pets with their owners if they exist
#img:link-data

select ?pet ?owner where {
  ?pet a / rdfs:subClassOf+ tto:Animal .
  optional {?owner tto:pet ?pet}
}


# Insert this triple in the dataset :
#
# dbpedia:Harrison_Ford tto:pet ttr:SnuffMonkey.
#
# (in Data tab from the menu and click on reload):
