#title:Search for lonely pets and try to find them a nice owner :)

#comment: Insert the triple using the data tab (you must be running in localhost)

#dbpedia:Harrison_Ford tto:pet ttr:SnuffMonkey.
#This query shows pet without owners

select ?pet ?owner where {
  ?pet a / rdfs:subClassOf+ tto:Animal .
  filter not exists {?owner tto:pet ?pet}
}