#title:Get Harrison Ford's pets, name and birth date 
#comment:Some information is retrieved from dbpedia (name, birth date) using a federated query  
#comment:through the SERVICE keyword. The graph retrieved is combined with the local graph
#comment:and solutions are built from the distant and local graph pattern matching processes.
#comment:The local graph pattern
#tags:1 graph pattern,VALUES,SERVICE
#color:ex-green

SELECT * where {
   dbpedia:Harrison_Ford tto:pet ?pet .
   SERVICE <http://dbpedia.org/sparql> {
       dbpedia:Harrison_Ford dbp:name ?name .
       dbpedia:Harrison_Ford dbp:birthDate ?bd .
	 }
}
