#id:NXQ_00040
#title:Get creature names, with their length, their first 2 characters (prefix), their last 2 characters (postfix)
#comment:Uses strlen() and substr() string functions to get the name length, first 2 and last 2 characters.
#comment:The function results are bound to the ?nameLength, ?namePrefix, ?namePostfix variables using BIND clauses.
#tags:1 graph pattern,4 variables,BIND,string function strlen(),string function substr()

select * where {
  ?thing dbp:name ?name .
  BIND ( ( strlen(?name))  as ?nameLength)
  BIND ( ( substr(?name, 1, 2))  as ?namePrefix)
  BIND ( ( substr(?name, ?nameLength-1, 2))  as ?namePostfix)
}
