#title:Select things that have a weight
#comment:Selects subjects described with the tto:weight predicate. 
#comment:?thing, ?weight are the variables
#tags:1 graph pattern,2 variables
    
select ?thing ?weight where {
  ?thing tto:weight ?weight . 
}
