#title:Select William's relatives (using both dbo:parent predicate path and inverse path)
#comment:retrieves solutions for objects connected to the subject ttr:William using the noraml and inverse path of the tto:friend predicate
#tags:1 graph pattern,1 variable,path syntax : inverse path ^,path syntax : alternative path |
#color:ex-violet

select * where {
  ttr:William dbo:parent | ^dbo:parent ?relatives.
}
