#id:NXQ_00105
#title:Get the count of pets by owner
#comment:Use the tto:pet predicate to link owners to pets,
#comment:In the SELECT variables, use the aggregate function COUNT() for pets,
#comment:Add a GROUP BY clause and use the owner as the group criterion.
#comment:The query should return 3 rows with 2 columns like:
#comment:ttr:John               "1"
#comment:ttr:William	        "2"
#comment:dbpedia:Harrison_Ford	"1"
#tags:1 graph pattern,2 variables,exercise level 2,GROUP BY,aggregate function COUNT()

SELECT ... {
	...
} GROUP BY ... 

