#id:NXQ_00107
#title:Get the person's names and the year they were born
#comment:Use the tto:type predicate to get people,
#comment:Use the YEAR() function to get the the sear they were born from their birth date 
#comment:and use BIND to assign the value returned to a new variable.
#comment:The query should return 3 rows with 2 columns like:
#comment:ttr:John       "1982"
#comment:ttr:William    "1988"
#comment:ttr:Eve        "1986"
#tags:2 graph patterns,2 variables,exercise level 2,BIND, date function YEAR()

SELECT ... {
	...
}
