#title:Get Creature class and its direct and sub classes
#comment:the ? after rdfs:subClassOf retrieves solutions for ?species if it is connected to tto:Creature by zero or one rdfs:subClassOf predicate
#tags:1 graph pattern,1 variable,path syntax : 0-1 path ?
#color:ex-yellow

select ?subSpecies where {
  ?subSpecies rdfs:subClassOf? tto:Creature .
}
