#title:For each owner of pets, get the list of his pets names
#comment:Use the tto:pet predicate to link owners to pets,
#comment:In the SELECT variables, use the aggregate function GROUP_CONCAT() to concatenate the pets names
#comment:Add a GROUP BY clause and use the owner as the group criterion.
#comment:The query should return 3 rows with 2 columns like:
#comment:ttr:John               "Buddy"
#comment:ttr:William            "Tom Luna"
#comment:dbpedia:Harrison_Ford  "Snuff"
#tags:2 graph patterns,2 variables,exercise level 2,GROUP BY,aggregate function GROUP_CONCAT()
#color:f7c5e0

SELECT ... {
	...
} GROUP BY ... 
